# Generated by Django 4.2.7 on 2025-06-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series', models.CharField(choices=[('A', 'ISO A Series'), ('B', 'ISO B Series'), ('NA', 'North American'), ('OTHER', 'Other')], max_length=10)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['series', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaperWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['gsm'],
            },
        ),
        migrations.AddField(
            model_name='papertype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='papertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductTypeSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper_sizes', models.ManyToManyField(related_name='product_types', to='products.papersize')),
                ('paper_types', models.ManyToManyField(related_name='product_types', to='products.papertype')),
                ('paper_weights', models.ManyToManyField(related_name='product_types', to='products.paperweight')),
                ('product_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='paperweight',
            name='paper_types',
            field=models.ManyToManyField(related_name='compatible_weights', to='products.papertype'),
        ),
        migrations.AddField(
            model_name='papersize',
            name='paper_weights',
            field=models.ManyToManyField(related_name='compatible_sizes', to='products.paperweight'),
        ),
        migrations.AlterUniqueTogether(
            name='papersize',
            unique_together={('width_mm', 'height_mm')},
        ),
    ]
