# Generated by Django 4.2.7 on 2025-06-01 04:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('auto_approve_users', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('system_maintenance', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('job_number_prefix', models.CharField(blank=True, max_length=20)),
                ('job_number_suffix', models.CharField(blank=True, max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('business_hours', models.JSONField(default=dict)),
                ('contact_info', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for', to='settings.branch')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
