# Generated by Django 4.2.7 on 2025-05-31 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocketCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=10, unique=True)),
                ('current_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'docket_counters',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(choices=[('BORROWDALE', 'Borrowdale'), ('PADDINGTON', 'Paddington')], max_length=20)),
                ('job_type', models.CharField(choices=[('LOCAL', 'Local'), ('FOREIGN', 'Foreign')], max_length=10)),
                ('docket_number', models.CharField(max_length=50, unique=True)),
                ('sales_rep', models.CharField(max_length=100)),
                ('order_taken_by', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('print_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('design_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PRINTED', 'Printed')], default='PENDING', max_length=10)),
                ('payment_status', models.CharField(choices=[('NOT_MARKED', 'Not Marked'), ('RECEIPTED', 'Receipted'), ('INVOICED', 'Invoiced')], default='NOT_MARKED', max_length=15)),
                ('payment_ref', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_cover_stock', to='products.papertype')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='products.producttype')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
