# Generated by Django 4.2.7 on 2025-06-01 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_papersize_paperweight_papertype_description_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cover_stock',
        ),
        migrations.RemoveField(
            model_name='job',
            name='size',
        ),
        migrations.RemoveField(
            model_name='job',
            name='stock',
        ),
        migrations.AddField(
            model_name='docketcounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='paper_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='products.papersize'),
        ),
        migrations.AddField(
            model_name='job',
            name='paper_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='products.papertype'),
        ),
        migrations.AddField(
            model_name='job',
            name='paper_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='products.paperweight'),
        ),
        migrations.AlterField(
            model_name='docketcounter',
            name='current_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='docketcounter',
            name='job_type',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('FOREIGN', 'Foreign')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='branch',
            field=models.CharField(choices=[('BORROWDALE', 'Borrowdale'), ('EASTLEA', 'Eastlea'), ('BELGRAVIA', 'Belgravia'), ('AVONDALE', 'Avondale'), ('MSASA', 'Msasa'), ('CHITUNGWIZA', 'Chitungwiza')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='design_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='docket_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='payment_status',
            field=models.CharField(choices=[('NOT_MARKED', 'Not Marked'), ('RECEIPTED', 'Receipted'), ('INVOICED', 'Invoiced')], default='NOT_MARKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='print_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRINTED', 'Printed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
